<?xml version="1.0" encoding="UTF-8"?>
<!-- Конфигуратор отдельно стоящей калитки - артикул DUS430 -->
<!-- Generated by Helpgen.py, version 2.44 beta ©  -->
<!-- Date: 2015-07-01 11:56 -->

<!DOCTYPE document
    [
        <!ELEMENT document (system, task, description, lanquage, table+)>
            <!ATTLIST   document
                        id        ID        #REQUIRED
                        type      NMTOKEN   #REQUIRED
            >
        <!ELEMENT system EMPTY>
            <!ATTLIST   system
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT task EMPTY>
            <!ATTLIST   task
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT description EMPTY>
            <!ATTLIST   description
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT lanquage EMPTY>
            <!ATTLIST   lanquage
                        id        ID        #REQUIRED
            >
        <!ELEMENT table (record+)>
            <!ATTLIST   table
                        name      NMTOKEN   #REQUIRED
            >
        <!ELEMENT record (field+)>
            <!ATTLIST   record
                        id        ID        #REQUIRED
            >
        <!ELEMENT field ANY>
            <!ATTLIST   field
                        name      NMTOKEN   #REQUIRED
            >
    ]
>


<document id='variablesContent' type='Respond'>
    <system id='-CIS' version='1'/>
    <task id='CALCHELPER' version='2'/>
    <description id='SingleWicketDUS430' version='1'/>
    <lanquage id='DEU'/>

    <table name='KnowledgeRepository'>
        <record id='c0'>
            <field name='image'>icon1.png</field>
            <field name='description'>Produkt- Configurator (WEB-Assistent). Benutzerhandbuch.</field>
            <field name='location'>documents/HelperInfo.pdf</field>
        </record>
    </table>

    <!-- ОПИСАНИЕ ГРУПП -->
    <table name='GroupAndSubgroup'>
        <record id='CompoundGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Bestellmöglichkeiten</field>
        </record>
        <record id='SquareInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Die Parameter der Öffnung</field>
        </record>
        <record id='square_clearance_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Просвет</field>
        </record>
        <record id='ProductInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Konstruktionsmerkmale</field>
        </record>
        <record id='shield_opening_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Направление открытия</field>
        </record>
        <record id='hinge_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Position der Scharniere</field>
        </record>
        <record id='GateShieldGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Щит калитки</field>
        </record>
        <record id='shield_delivery_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Изготовление</field>
        </record>
        <record id='shield_form_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Форма</field>
        </record>
        <record id='shield_body_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Заполнение</field>
        </record>
        <record id='hinged_rack_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Навесная рама</field>
        </record>
        <record id='lattice_property_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Высота решетки (R)</field>
        </record>
        <record id='pic_height_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Высота пик (N)</field>
        </record>
        <record id='arch_height_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Высота арки (S)</field>
        </record>
        <record id='SandwichPanelGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Sandwich-Paneele</field>
        </record>
        <record id='outer_side_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Design</field>
        </record>
        <record id='outer_composition_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Struktur</field>
        </record>
        <record id='premium_design_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Варианты оформления Premium</field>
        </record>
        <record id='outer_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Farbe</field>
        </record>
        <record id='InnerSideGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Оформление с внутренней стороны</field>
        </record>
        <record id='AluminiumProfileGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Алюминиевый профиль</field>
        </record>
        <record id='sash_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Profilfarbe</field>
        </record>
        <record id='EdgingGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Окантовка</field>
        </record>
        <record id='edging_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Farbe der Kantenprofile</field>
        </record>
        <record id='PowerRackGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Силовая рама</field>
        </record>
        <record id='rack_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Рама калитки</field>
        </record>
        <record id='rack_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет силовой рамы</field>
        </record>
        <record id='color_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Тип краски</field>
        </record>
        <record id='HandleAndLockGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Ручки и задвижки</field>
        </record>
        <record id='lock_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Замок</field>
        </record>
        <record id='aluminium_handle_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Ручка калитки</field>
        </record>
        <record id='HandleInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Примечание к выбору ручки</field>
        </record>
        <record id='EquipmentGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Optionales Zubehör</field>
        </record>
        <record id='PackagingGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Produktverpackung</field>
        </record>
        <record id='HingedRackInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Примечание к выбору навесной рамы</field>
        </record>
        <record id='NoteGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Hinweis</field>
        </record>
    </table>

    <!-- РАЗДЕЛ ДЛЯ ПОЛЕЙ ФОРМЫ КОНФИГУРАТОРА -->
    <table name='HelperTaskDescription'>
        <record id='SquareWidth'>
            <field name='Label'>Breite (B)</field>
            <field name='Description'>Значение ширины проёма для установки калитки.</field>
        </record>
        <record id='SquareHeight'>
            <field name='Label'>Höhe (H)</field>
            <field name='Description'>Значение высоты проёма для установки калитки.</field>
        </record>
        <record id='SquareAperture'>
            <field name='Label'>Die Gesamtfläche der Öffnung</field>
            <field name='Description'>Значение высоты проёма для установки калитки.</field>
        </record>
        <record id='SquareClearance'>
            <field name='Label'>Просвет (P)</field>
            <field name='Description'></field>
        </record>
        <record id='Opening_Outside'>
            <field name='Label'>Наружу</field>
            <field name='Description'>Направление определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Opening_Inside'>
            <field name='Label'>Внутрь</field>
            <field name='Description'>Направление определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Hinge_Left'>
            <field name='Label'>Links</field>
            <field name='Description'>Положение петель определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Hinge_Right'>
            <field name='Label'>Rechts</field>
            <field name='Description'>Положение петель определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='ShieldDelivery_Default'>
            <field name='Label'>В сборе</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldDelivery_Out'>
            <field name='Label'>В разборе</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldForm_Default'>
            <field name='Label'>Прямоугольная</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldForm_Arch'>
            <field name='Label'>Арочная</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldBody_Default'>
            <field name='Label'>Из сэндвич панелей</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldBody_Aluminium_Profile'>
            <field name='Label'>Из алюминиевых профилей</field>
            <field name='Description'></field>
        </record>
        <record id='HingedRack_WithoutJumper'>
            <field name='Label'>Без перемычки</field>
            <field name='Description'></field>
        </record>
        <record id='HingedRack_WithJumper'>
            <field name='Label'>С перемычкой</field>
            <field name='Description'></field>
        </record>
        <record id='HingedRack_No'>
            <field name='Label'>Nein</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldDesign_Standard'>
            <field name='CurrentValue'>Модель щита по каталогу:</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldGroupTitle_1'>
            <field name='CurrentValue'>____________</field>
            <field name='Description'></field>
        </record>
        <record id='LatticeHeight'>
            <field name='Label'>Высота решётки (R)</field>
            <field name='Description'></field>
        </record>
        <record id='PicHeight'>
            <field name='Label'>Высота пик (N)</field>
            <field name='Description'></field>
        </record>
        <record id='ArchHeight'>
            <field name='Label'>Высота арки (S)</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldOuterDesignTitle_1'>
            <field name='CurrentValue'>Внешняя сторона</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterDesign_List'>
            <field name='Label'>Design</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterComposition_List'>
            <field name='Label'>Struktur</field>
            <field name='Description'>Структура поверхности сэндвич-панелей.</field>
        </record>
        <record id='PremiumDesign_A'>
            <field name='Label'>В-1</field>
            <field name='Description'>Вариант оформления сэндвич-панелей Premium #1 - по умолчанию.</field>
        </record>
        <record id='PremiumDesign_B'>
            <field name='Label'>В-2</field>
            <field name='Description'>Вариант оформления сэндвич-панелей Premium #2.</field>
        </record>
        <record id='PremiumDesign_C'>
            <field name='Label'>В-3</field>
            <field name='Description'>Вариант оформления сэндвич-панелей Premium #3.</field>
        </record>
        <record id='PremiumDesign_D'>
            <field name='Label'>В-4</field>
            <field name='Description'>Вариант оформления сэндвич-панелей Premium #4.</field>
        </record>
        <record id='OuterColorStandard'>
            <field name='Label'>Standard -Farben (RAL)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorNonStandard'>
            <field name='Label'>Нестандартный</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorWood'>
            <field name='Label'>Имитации дерева</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColor_Custom'>
            <field name='Label'>Individuell (nach Modell)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='InnerGroupTitle_1'>
            <field name='CurrentValue'>____________</field>
            <field name='Description'></field>
        </record>
        <record id='InnerPremiumSetup'>
            <field name='Label'>Дизайн PREMIUM с внутренней стороны</field>
            <field name='Description'></field>
        </record>
        <record id='SashColorStandard'>
            <field name='Label'>Standard</field>
            <field name='Description'>Цвет окантовочных профилей рамы калитки.</field>
        </record>
        <record id='SashColorNonStandard'>
            <field name='Label'>Нестандартный</field>
            <field name='Description'>Цвет окантовочных профилей рамы калитки.</field>
        </record>
        <record id='SashColor_Custom'>
            <field name='Label'>Gem. RAL- Farbmuster (4-stellig)</field>
            <field name='Description'>Цвет окантовочных профилей рамы калитки.</field>
        </record>
        <record id='EdgingColorStandard'>
            <field name='Label'>В цвет полотна</field>
            <field name='Description'></field>
        </record>
        <record id='EdgingColorNonStandard'>
            <field name='Label'>На выбор</field>
            <field name='Description'></field>
        </record>
        <record id='EdgingColor_Custom'>
            <field name='Label'>Gem. RAL- Farbmuster (4-stellig)</field>
            <field name='Description'></field>
        </record>
        <record id='WithRack_List'>
            <field name='Label'>Рама калитки</field>
            <field name='Description'>По умолчанию в составе калитки предусмотрена задвижка, возможности выбора и установки замков нет.</field>
        </record>
        <record id='RackColorGroupTitle_1'>
            <field name='CurrentValue'>_________</field>
            <field name='Description'></field>
        </record>
        <record id='RackColorGroupTitle_2'>
            <field name='CurrentValue'>Оформление силовой рамы:</field>
            <field name='Description'></field>
        </record>
        <record id='RackColorStandard'>
            <field name='Label'>В цвет полотна</field>
            <field name='Description'></field>
        </record>
        <record id='RackColorNonStandard'>
            <field name='Label'>На выбор</field>
            <field name='Description'></field>
        </record>
        <record id='RackColor_Custom'>
            <field name='Label'>Gem. RAL- Farbmuster (4-stellig)</field>
            <field name='Description'></field>
        </record>
        <record id='RackColorType_Mat'>
            <field name='Label'>Матовая</field>
            <field name='Description'></field>
        </record>
        <record id='RackColorType_Glossy'>
            <field name='Label'>Глянцевая</field>
            <field name='Description'></field>
        </record>
        <record id='WithLock_List'>
            <field name='Label'>Замок</field>
            <field name='Description'>По умолчанию в составе калитки предусмотрена задвижка, возможности выбора и установки замков нет. При выборе электромеханического замка Nuova Feb или CISA в комплект входит стандартная ручка.</field>
        </record>
        <record id='WithAluminiumHandle_List'>
            <field name='Label'>Ручка алюминиевая</field>
            <field name='Description'></field>
        </record>
        <record id='AdditionalDevices_3'>
            <field name='CurrentValue'>Бетон на 1 столб</field>
            <field name='Description'></field>
        </record>
        <record id='AdditionalDevices_4'>
            <field name='CurrentValue'>Бетон для рамы бетонируемой</field>
            <field name='Description'></field>
        </record>
        <record id='AdditionalDevices_11'>
            <field name='CurrentValue'>Комплект лежачего полицейского L=1000 мм</field>
            <field name='Description'></field>
        </record>
        <record id='AdditionalDevices_12'>
            <field name='CurrentValue'>Комплект боковых крышек для резинового полицейского</field>
            <field name='Description'></field>
        </record>
        <record id='Packaging_Styrofoam'>
            <field name='Label'>PVC- Laminierung</field>
            <field name='Description'>Выбор дополнительной упаковки в случае требований заказчика.</field>
        </record>
        <record id='Packaging_Cardboard'>
            <field name='Label'>Karton</field>
            <field name='Description'>Выбор дополнительной упаковки в случае требований заказчика.</field>
        </record>
        <record id='Note'>
            <field name='Label'></field>
            <field name='Description'>Auswahl zusätzlicher Verpackung, auf Anforderung des Kunden. Standardverpackung: Schutzecken, Stretchfolie.</field>
        </record>

        <!-- РАЗДЕЛ КОНСТАНТ -->
        <record id='default_nonstandard_code'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>---</field>
        </record>

        <record id='default_rack_color'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>8014</field>
        </record>

        <record id='default_square_clearance'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>100</field>
        </record>

        <record id='default_square_overfall'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>0</field>
        </record>

        <record id='default_column_material'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>perforated_brick</field>
        </record>

        <record id='default_fence_material'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>brick</field>
        </record>

        <record id='default_ground_material'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>ground</field>
        </record>

        <record id='default_lattice_height'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>200</field>
        </record>

        <record id='default_lattice_step'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>0</field>
        </record>

        <record id='default_outer_design'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_composition'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>Stucco</field>
        </record>

        <record id='default_outer_color_standard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_color_wood'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_color_premium'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_color_custom'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_inner_design'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>Гофра (классический)</field>
        </record>

        <record id='default_inner_composition'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>Stucco</field>
        </record>

        <record id='default_inner_color_standard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_inner_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_inner_color_wood'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_inner_color_premium'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_inner_color_custom'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>9003</field>
        </record>

        <record id='default_edging_color_standard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>8014</field>
        </record>

        <record id='default_edging_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_edging_color_custom'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_sash_color_standard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>8014</field>
        </record>

        <record id='default_sash_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_sash_color_custom'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_rack_color_standard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>8014</field>
        </record>

        <record id='default_rack_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_rack_color_custom'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_with_rack'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>hanging_poles</field>
        </record>

        <record id='default_with_lock'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_with_aluminium_handle'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_with_handle'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='word_more'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>более</field>
        </record>

        <record id='word_less'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>менее</field>
        </record>

        <record id='word_width_more_then'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>ширина более</field>
        </record>

        <record id='word_and'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>и</field>
        </record>

        <record id='word_not_defined'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>nicht definiert</field>
        </record>

        <record id='SquareHeightMessage'>
            <field name='CurrentValue'>Die Höhe muss mindestens 1000 mm und nicht mehr als 1000 mm sein.</field>
        </record>

        <record id='SquareWidthMessage'>
            <field name='CurrentValue'>Die Breite muss mindestens 600 mm und nicht mehr als 600 mm betragen.</field>
        </record>

        <record id='ExtraSquareHeightMessage'>
            <field name='CurrentValue'>Если CCC, значение высоты должно быть не --- XXX мм.</field>
        </record>

        <record id='ExtraSquareWidthMessage'>
            <field name='CurrentValue'>Недопустимая ширина проёма. Значение ширины проёма должно удовлетворять следующим диапазонам: 900-950, 1035-1085, 1170-1220, 1305-1355, 1440-1490 мм.</field>
        </record>

        <record id='LatticeHeightMessage'>
            <field name='CurrentValue'>Высота решётки не может быть менее 200 мм. или более XXX мм.</field>
        </record>

        <record id='LatticeStepMessage'>
            <field name='CurrentValue'>Шаг решётки должен быть не менее 100 мм. и не более 120 мм.</field>
        </record>

        <record id='DoorSideHeightMessage'>
            <field name='CurrentValue'>Значение высоты [] должно быть не менее  мм. и не более XXX мм.</field>
        </record>

        <record id='DoorSideWidthMessage'>
            <field name='CurrentValue'>Значение ширины [] должно быть не менее  мм. и не более  мм.</field>
        </record>

        <record id='SidePanelMessage'>
            <field name='CurrentValue'>Филенка может использоваться только с одной стороны (внешней или внутренней).</field>
        </record>

        <record id='WaveMessage'>
            <field name='CurrentValue'>Дизайн "Волна" для выбранного региона недоступен.</field>
        </record>

        <record id='PicHeightMessage'>
            <field name='CurrentValue'>Высота пик должна быть не менее MIN мм. и не более MAX мм.</field>
        </record>

        <record id='ArchHeightMessage'>
            <field name='CurrentValue'>Высота арки должна быть не менее MIN мм. и не более MAX мм.</field>
        </record>

        <record id='ExtraArchHeightMessage'>
            <field name='CurrentValue'>Предельное значение высоты арки XXX мм.</field>
        </record>

        <record id='SquareClearanceMessage'>
            <field name='CurrentValue'>Величина просвета должна быть не менее 35 мм. и не более 150 мм.</field>
        </record>

        <record id='SquareOverfallMessage'>
            <field name='CurrentValue'>Величина перепада должна быть не менее 0 мм. и не более 150 мм.</field>
        </record>

        <record id='HeightMessage'>
            <field name='CurrentValue'>Значение ВЫСОТЫ проема для установки полотна калитки от 1 до 3,8 м.
Стандартная сэндвич панель- максимальное значение 3,2 м;
Алюминиевая сэндвич панель- максимальное значение 3,8 м;
Алюминиевый профиль (сплошной)- максимальное значение 3 м;
Алюминиевый профиль (решетка)- максимальное значение 2 м;
Premium1 и Premium2- максимальное значение 3 м.</field>
        </record>

        <record id='WidthMessage'>
            <field name='CurrentValue'>Значение ШИРИНЫ проема для установки полотна калитки от 2 до 9 м.
Стандартная сэндвич панель – максимальное значение 7,5 м;
Алюминиевая сэндвич панель- максимальное значение 9 м;
Алюминиевый профиль (сплошной)- максимальное значение 4 м;
Алюминиевый профиль (решетка) – максимальное значение 3,5 м;