<?xml version="1.0" encoding="UTF-8"?>
<!-- Конфигуратор секционных промышленных ворот стандартной серии - артикул DUS480 -->
<!-- Generated by Helpgen.py, version 2.44 beta ©  -->
<!-- Date: 2015-06-25 01:03 -->

<!DOCTYPE document
    [
        <!ELEMENT document (system, task, description, lanquage, table+)>
            <!ATTLIST   document
                        id        ID        #REQUIRED
                        type      NMTOKEN   #REQUIRED
            >
        <!ELEMENT system EMPTY>
            <!ATTLIST   system
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT task EMPTY>
            <!ATTLIST   task
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT description EMPTY>
            <!ATTLIST   description
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT lanquage EMPTY>
            <!ATTLIST   lanquage
                        id        ID        #REQUIRED
            >
        <!ELEMENT table (record+)>
            <!ATTLIST   table
                        name      NMTOKEN   #REQUIRED
            >
        <!ELEMENT record (field+)>
            <!ATTLIST   record
                        id        ID        #REQUIRED
            >
        <!ELEMENT field ANY>
            <!ATTLIST   field
                        name      NMTOKEN   #REQUIRED
            >
    ]
>


<document id='variablesContent' type='Respond'>
    <system id='-CIS' version='1'/>
    <task id='CALCHELPER' version='2'/>
    <description id='SectionalDoorsDUS480' version='1'/>
    <lanquage id='RUS'/>

    <table name='KnowledgeRepository'>
        <record id='c0'>
            <field name='image'>icon1.png</field>
            <field name='description'>Конфигуратор изделий (WEB-помощник). Руководство пользователя.</field>
            <field name='location'>documents/HelperInfo.pdf</field>
        </record>
        <record id='c1'>
            <field name='image'>icon1.png</field>
            <field name='description'>Каталог комплектации для секционных ворот .</field>
            <field name='location'>documents/katalog_sekcionnie_sistemi_2013-RUS.pdf</field>
        </record>
    </table>

    <!-- ОПИСАНИЕ ГРУПП -->
    <table name='GroupAndSubgroup'>
        <record id='CompoundGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Комплектация заказа</field>
        </record>
        <record id='GarageInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Параметры проёма</field>
        </record>
        <record id='platband_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Притолока</field>
        </record>
        <record id='left_side_width_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Левый пристенок</field>
        </record>
        <record id='right_side_width'>
            <field name='TypeID'>2</field>
            <field name='Description'>Правый пристенок</field>
        </record>
        <record id='depth_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Глубина помещения</field>
        </record>
        <record id='wall_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Материал стен</field>
        </record>
        <record id='ceiling_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Материал потолка</field>
        </record>
        <record id='lintel_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Материал притолоки</field>
        </record>
        <record id='ProductInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Особенности конструкции</field>
        </record>
        <record id='lifting_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Тип подъёма</field>
        </record>
        <record id='slope_angle_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Угол наклона</field>
        </record>
        <record id='lifting_cycle_count_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Количество циклов (шт)</field>
        </record>
        <record id='SandwichPanelGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Сэндвич-панели</field>
        </record>
        <record id='outer_side_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Дизайн</field>
        </record>
        <record id='outer_composition_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Структура</field>
        </record>
        <record id='outer_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет</field>
        </record>
        <record id='InnerSideGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Оформление с внутренней стороны</field>
        </record>
        <record id='DoorGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Калитка</field>
        </record>
        <record id='door_setup_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Встроить калитку</field>
        </record>
        <record id='door_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Тип калитки</field>
        </record>
        <record id='door_side_width_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Ширина проёма для калитки</field>
        </record>
        <record id='door_side_height_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Высота проёма для калитки</field>
        </record>
        <record id='door_position_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Положение калитки на полотне ворот</field>
        </record>
        <record id='hinge_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Положение петель</field>
        </record>
        <record id='door_sash_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет профиля калитки</field>
        </record>
        <record id='DoorLockGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Замки и задвижки</field>
        </record>
        <record id='lock_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Замок</field>
        </record>
        <record id='dleGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Ручки</field>
        </record>
        <record id='handle_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Дополнительная ручка</field>
        </record>
        <record id='AcrylicWindowGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Акриловые окна</field>
        </record>
        <record id='acrylic_window_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Количество по типам</field>
        </record>
        <record id='window_note_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Примечания к выбору окон</field>
        </record>
        <record id='GuardDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Механизмы защиты</field>
        </record>
        <record id='DriveGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Автоматика</field>
        </record>
        <record id='drive_setup_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Установить привод</field>
        </record>
        <record id='drive_model_overhead_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Потолочный</field>
        </record>
        <record id='drive_model_power_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Вальный</field>
        </record>
        <record id='drive_model_manual_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Ручной</field>
        </record>
        <record id='ProductConfirmationGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Конструкторский контроль</field>
        </record>
        <record id='ControlDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Устройства управления</field>
        </record>
        <record id='SecurityDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Устройства безопасности</field>
        </record>
        <record id='EquipmentGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Дополнительная комплектация</field>
        </record>
        <record id='edging_pipe_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет окантовочной трубы</field>
        </record>
        <record id='ExpendableMaterialsGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Расходные материалы</field>
        </record>
        <record id='NoteGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Примечание</field>
        </record>
    </table>

    <!-- РАЗДЕЛ ДЛЯ ПОЛЕЙ ФОРМЫ КОНФИГУРАТОРА -->
    <table name='HelperTaskDescription'>
        <record id='Compound_Default'>
            <field name='Label'>Комплект ворот</field>
            <field name='Description'></field>
        </record>
        <record id='Compound_ShieldOnly'>
            <field name='Label'>Щит ворот без комплектации</field>
            <field name='Description'></field>
        </record>
        <record id='Compound_SlideRailsOnly'>
            <field name='Label'>Направляющие ворот без комплектации</field>
            <field name='Description'></field>
        </record>
        <record id='SquareWidth'>
            <field name='Label'>Ширина (B)</field>
            <field name='Description'>Значение ширины проёма для установки полотна ворот.</field>
        </record>
        <record id='SquareHeight'>
            <field name='Label'>Высота (H)</field>
            <field name='Description'>Значение высоты проёма для установки полотна ворот.</field>
        </record>
        <record id='SquareAperture'>
            <field name='Label'>Общая площадь проёма</field>
            <field name='Description'>Значение высоты проёма для установки полотна ворот.</field>
        </record>
        <record id='Platband_Size'>
            <field name='Label'>Притолока (h)</field>
            <field name='Description'>Притолока - это расстояние от верхнего края проёма до потолка.</field>
        </record>
        <record id='LeftSideWidth'>
            <field name='Label'>Левый пристенок (b1)</field>
            <field name='Description'>Расстояние от края проёма до левой стены помещения.</field>
        </record>
        <record id='RightSideWidth'>
            <field name='Label'>Правый пристенок (b2)</field>
            <field name='Description'>Расстояние от края проёма до правой стены помещения.</field>
        </record>
        <record id='SquareDepthGroupTitle_1'>
            <field name='CurrentValue'>_________</field>
            <field name='Description'></field>
        </record>
        <record id='SquareDepth'>
            <field name='Label'>Глубина помещения (L)</field>
            <field name='Description'></field>
        </record>
        <record id='WallMaterialTitle_1'>
            <field name='CurrentValue'>Материал стен:</field>
            <field name='Description'>Тип материала проёма для правильного выбора крепежа.</field>
        </record>
        <record id='WallMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Тип материала проёма для правильного выбора крепежа.</field>
        </record>
        <record id='CeilingMaterialTitle_1'>
            <field name='CurrentValue'>Материал потолка:</field>
            <field name='Description'>Тип материала потолка для правильного выбора крепежа.</field>
        </record>
        <record id='CeilingMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Тип материала потолка для правильного выбора крепежа.</field>
        </record>
        <record id='LintelMaterialTitle_1'>
            <field name='CurrentValue'>Материал притолоки:</field>
            <field name='Description'>Тип материала притолоки для правильного выбора крепежа.</field>
        </record>
        <record id='LintelMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Тип материала притолоки для правильного выбора крепежа.</field>
        </record>
        <record id='LiftingType_LowRollFront'>
            <field name='Label'>Низкий (барабан спереди)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_LowRollBack'>
            <field name='Label'>Низкий (барабан сзади)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Default'>
            <field name='Label'>Стандартный</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Downward'>
            <field name='Label'>Стандартный наклонный</field>
            <field name='Description'>Значение вводимое в поле «Угол подъема (град.)» должно быть кратным 5. (Пример: 5,10,15,20……65)».</field>
        </record>
        <record id='LiftingType_High'>
            <field name='Label'>Высокий</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_HighRollBottom'>
            <field name='Label'>Высокий (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_HighDownward'>
            <field name='Label'>Высокий наклонный</field>
            <field name='Description'>Значение вводимое в поле «Угол подъема (град.)» должно быть кратным 5. (Пример: 5,10,15,20……65)».</field>
        </record>
        <record id='LiftingType_HighDownwardRollBottom'>
            <field name='Label'>Высокий наклонный (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Vertical'>
            <field name='Label'>Вертикальный</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_VerticalRollBottom'>
            <field name='Label'>Вертикальный (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='SlopeAngle'>
            <field name='Label'>Угол наклона (град.)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25130LG'>
            <field name='Label'>25 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25130'>
            <field name='Label'>50 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25131LG'>
            <field name='Label'>75 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25131'>
            <field name='Label'>100 000</field>
            <field name='Description'></field>
        </record>
        <record id='ProductInfoGroupTitle_1'>
            <field name='CurrentValue'>________________________</field>
            <field name='Description'></field>
        </record>
        <record id='IsOptimizeLifting'>
            <field name='Label'>Оптимальный подъём</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldOuterDesignTitle_1'>
            <field name='CurrentValue'>Внешняя сторона</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterDesign_List'>
            <field name='Label'>Дизайн</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterComposition_List'>
            <field name='Label'>Структура</field>
            <field name='Description'>Структура поверхности сэндвич-панелей.</field>
        </record>
        <record id='OuterColorStandard'>
            <field name='Label'>Стандартный (RAL)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorNonStandard'>
            <field name='Label'>Нестандартный</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorWood'>
            <field name='Label'>Имитации дерева</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColor_Custom'>
            <field name='Label'>Индивидуальный (по образцу)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='DoorSetup'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V2'>
            <field name='Label'>V2</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V3'>
            <field name='Label'>V3</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V4'>
            <field name='Label'>V4</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V5'>
            <field name='Label'>V5</field>
            <field name='Description'></field>
        </record>
        <record id='DoorSideGroupTitle_1'>
            <field name='CurrentValue'>Размеры калитки:</field>
            <field name='Description'>Ширина калитки от 800 до 1000 мм, калитка версии V3 шириной 800 мм.</field>
        </record>
        <record id='DoorSideWidth'>
            <field name='Label'>Ширина (b)</field>
            <field name='Description'>Ширина калитки от 800 до 1000 мм, калитка версии V3 шириной 800 мм.</field>
        </record>
        <record id='DoorSideHeight'>
            <field name='Label'>Высота (h)</field>
            <field name='Description'>Допустимые значения высоты калитки от 1800 до 2300 мм. В зависимости от раскроя панелей полотна ворот высота калитки может варьироваться от 0 до 150 мм.</field>
        </record>
        <record id='DoorSideGroupTitle_2'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'>Допустимые значения высоты калитки от 1800 до 2300 мм. В зависимости от раскроя панелей полотна ворот высота калитки может варьироваться от 0 до 150 мм.</field>
        </record>
        <record id='DoorPosition_Left'>
            <field name='Label'>Слева</field>
            <field name='Description'>Положение встроенной калитки относительно левого края полотна ворот (расстояние от левого края полотна ворот). Расстояние в мм. Положение калитки определяется наблюдателем, находящимся внутри помещения.</field>
        </record>
        <record id='DoorPosition_Center'>
            <field name='Label'>По центру</field>
            <field name='Description'>Положение встроенной калитки относительно левого края полотна ворот (расстояние от левого края полотна ворот). Расстояние в мм. Положение калитки определяется наблюдателем, находящимся внутри помещения.</field>
        </record>
        <record id='DoorPosition_Right'>
            <field name='Label'>Справа</field>
            <field name='Description'>Положение встроенной калитки относительно левого края полотна ворот (расстояние от левого края полотна ворот). Расстояние в мм. Положение калитки определяется наблюдателем, находящимся внутри помещения.</field>
        </record>
        <record id='Hinge_Left'>
            <field name='Label'>Слева</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='Hinge_Right'>
            <field name='Label'>Справа</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='DoorSideGroupTitle_3'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='DoorSashColorStandard'>
            <field name='Label'>Стандартный</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='DoorSashColor_List'>
            <field name='Label'>Цвет профиля</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='DoorSashColor_BySample'>
            <field name='Label'>По образцу RAL (4-х значное число)</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='WithLock_List'>
            <field name='Label'>Замок</field>
            <field name='Description'></field>
        </record>
        <record id='WithHandle_List'>
            <field name='Label'>Дополнительная ручка</field>
            <field name='Description'>Можно установить только одну дополнительную ручку.</field>
        </record>
        <record id='Window_DH85603'>
            <field name='CurrentValue'>635х330 мм, акриловое</field>
            <field name='Description'>Тип и размеры окна, устанавливаемого в полотно ворот.</field>
        </record>
        <record id='Window_DH85602'>
            <field name='CurrentValue'>607х202 мм, акриловое</field>
            <field name='Description'>Тип и размеры окна, устанавливаемого в полотно ворот.</field>
        </record>
        <record id='Window_RingSilver'>
            <field name='CurrentValue'>Окно круглое, диаметр 360 мм, металик</field>
            <field name='Description'>Тип и размеры окна, устанавливаемого в полотно ворот.</field>
        </record>
        <record id='WindowNote'>
            <field name='Label'>Примечания к выбору окон</field>
            <field name='Description'>Описание размещения окон на полотне ворот.</field>
        </record>
        <record id='WithGuardRope'>
            <field name='Label'>Устройство безопасности тросса</field>
            <field name='Description'></field>
        </record>
        <record id='WithGuardBreakRope'>
            <field name='Label'>Устройство защиты от разрыва тросса</field>
            <field name='Description'></field>
        </record>
        <record id='DriveSetup'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSetupFuture'>
            <field name='Label'>Будущая установка вального привода</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSetupGroupTitle_3'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelOverheadStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelGroupTitle_1'>
            <field name='CurrentValue'>Комплект потолочного привода:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelGroupTitle_2'>
            <field name='CurrentValue'>Привод:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500PROWHITE'>
            <field name='Label'>SECTIONAL-500PRO-WHITE S=8 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500PROBLACK'>
            <field name='Label'>SECTIONAL-500PRO-BLACK S=8 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500'>
            <field name='Label'>SECTIONAL-500</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE750'>
            <field name='Label'>SECTIONAL-750</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_FAST750'>
            <field name='Label'>FAST-750</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE1000'>
            <field name='Label'>SECTIONAL-1000, S=13 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE1200'>
            <field name='Label'>SECTIONAL-1200</field>
            <field name='Description'></field>
        </record>
        <record id='OverheadDeviceGroupTitle_1'>
            <field name='CurrentValue'>Комплект направляющих для потолочного привода:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerGroupTitle_1'>
            <field name='CurrentValue'>Комплект вального привода:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerGroupTitle_2'>
            <field name='CurrentValue'>Привод:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXPower_SE524'>
            <field name='Label'>GFA SE-5.24 220V</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXPower_SE1421'>
            <field name='Label'>GFA SE-14.21 380V</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSideGroupTitle_1'>
            <field name='CurrentValue'>Сторона установки привода:</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSide_Right'>
            <field name='Label'>Справа</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSide_Left'>
            <field name='Label'>Слева</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelManualStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025M'>
            <field name='Label'>Ручной цепной привод</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025KIT'>
            <field name='Label'>Ручной цепной привод с роликом</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025P'>
            <field name='Label'>Ручной цепной привод со звёздочкой</field>
            <field name='Description'></field>
        </record>
        <record id='DriveExtraChainGroupTitle_1'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'></field>
        </record>
        <record id='DriveExtraChain'>
            <field name='Label'>Дополнительная цепь</field>
            <field name='Description'>Необходимое количество дополнительной цепи рассчитывается в метрах с округлением до ближайшего целого в большую сторону.</field>
        </record>
        <record id='ControlDevicesGroup_COMMAND433'>
            <field name='CurrentValue'>Кнопочная панель радиоуправления COMMAND433</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_XT2_868SLH'>
            <field name='CurrentValue'>Пульт 2-канальный  (БЕЛЫЙ)</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_RX_RP1_868_SLH'>
            <field name='CurrentValue'>Приемник 868 МГЦ (встраеваемый) со встр. антеной</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_Transmitter_2'>
            <field name='CurrentValue'>Пульт  2-х канальный, 433МГц</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_Transmitter_4'>
            <field name='CurrentValue'>Пульт  4-х канальный, 433МГц</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_RCBLACK_4'>