<?xml version="1.0" encoding="UTF-8"?>
<!-- Конфигуратор калитки для системы ограждений - артикул DUS-931 -->
<!-- Generated by Helpgen.py, version 2.37 beta ©  -->
<!-- Date: 2014-09-13 07:49 -->

<!DOCTYPE document
    [
        <!ELEMENT document (system, task, description, lanquage, table+)>
            <!ATTLIST   document
                        id        ID        #REQUIRED
                        type      NMTOKEN   #REQUIRED
            >
        <!ELEMENT system EMPTY>
            <!ATTLIST   system
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT task EMPTY>
            <!ATTLIST   task
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT description EMPTY>
            <!ATTLIST   description
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT lanquage EMPTY>
            <!ATTLIST   lanquage
                        id        ID        #REQUIRED
            >
        <!ELEMENT table (record+)>
            <!ATTLIST   table
                        name      NMTOKEN   #REQUIRED
            >
        <!ELEMENT record (field+)>
            <!ATTLIST   record
                        id        ID        #REQUIRED
            >
        <!ELEMENT field ANY>
            <!ATTLIST   field
                        name      NMTOKEN   #REQUIRED
            >
    ]
>


<document id='variablesContent' type='Respond'>
    <system id='-CIS' version='1'/>
    <task id='CALCHELPER' version='2'/>
    <description id='FenceWicketDUS931' version='1'/>
    <lanquage id='ENG'/>

    <table name='KnowledgeRepository'>
        <record id='c0'>
            <field name='image'>icon1.png</field>
            <field name='description'> products WEB-helper. Users manual (in Russian only).</field>
            <field name='location'>documents/HelperInfo.pdf</field>
        </record>
        <record id='c1'>
            <field name='image'>icon1.png</field>
            <field name='description'>Каталог "СИСТЕМЫ ОГРАЖДЕНИЙ Velli ()"</field>
            <field name='location'>documents/catalog-fence-systems.pdf</field>
        </record>
    </table>

    <!-- ОПИСАНИЕ ГРУПП -->
    <table name='GroupAndSubgroup'>
        <record id='CompoundGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Order options</field>
        </record>
        <record id='ModelGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Parameters of the opening</field>
        </record>
        <record id='square_clearance_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Просвет</field>
        </record>
        <record id='ProductInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Features</field>
        </record>
        <record id='shield_opening_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Направление открытия</field>
        </record>
        <record id='hinge_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Position of hinges</field>
        </record>
        <record id='assembly_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Монтаж калитки</field>
        </record>
        <record id='SandwichPanelGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Design</field>
        </record>
        <record id='outer_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет полотна калитки</field>
        </record>
        <record id='color_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Тип краски</field>
        </record>
        <record id='HandleAndLockGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Optional equipment</field>
        </record>
        <record id='lock_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Замок</field>
        </record>
        <record id='ExpendableMaterialsGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Consumables</field>
        </record>
        <record id='PackagingGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Product packaging</field>
        </record>
        <record id='NoteGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Note</field>
        </record>
    </table>

    <!-- РАЗДЕЛ ДЛЯ ПОЛЕЙ ФОРМЫ КОНФИГУРАТОРА -->
    <table name='HelperTaskDescription'>
        <record id='SquareWidth_List'>
            <field name='Label'>Width (B)</field>
            <field name='Description'>Значение ширины проёма для установки калитки.</field>
        </record>
        <record id='SquareHeight_List'>
            <field name='Label'>Height (H)</field>
            <field name='Description'>Значение высоты проёма для установки калитки.</field>
        </record>
        <record id='SquareAperture'>
            <field name='Label'>Total area of the opening</field>
            <field name='Description'>Значение высоты проёма для установки калитки.</field>
        </record>
        <record id='SquareClearanceGroupTitle_1'>
            <field name='CurrentValue'>_________</field>
            <field name='Description'></field>
        </record>
        <record id='SquareClearance'>
            <field name='Label'>Просвет (P)</field>
            <field name='Description'></field>
        </record>
        <record id='Opening_Outside'>
            <field name='Label'>Наружу</field>
            <field name='Description'>Направление открытия определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Opening_Inside'>
            <field name='Label'>Внутрь</field>
            <field name='Description'>Направление открытия определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Hinge_Left'>
            <field name='Label'>On the left</field>
            <field name='Description'>Положение петель определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='Hinge_Right'>
            <field name='Label'>On the right</field>
            <field name='Description'>Положение петель определяется наблюдателем, находящимся внутри усадьбы или огороженной территории.</field>
        </record>
        <record id='AssemblyGroupTitle_1'>
            <field name='CurrentValue'>_________</field>
            <field name='Description'>По умолчанию в составе калитки предусмотрена задвижка, возможности выбора и установки замков нет.</field>
        </record>
        <record id='AssemblyType_List'>
            <field name='Label'>Монтаж калитки</field>
            <field name='Description'>По умолчанию в составе калитки предусмотрена задвижка, возможности выбора и установки замков нет.</field>
        </record>
        <record id='OuterColorStandard'>
            <field name='Label'>Standard</field>
            <field name='Description'>Цвет  полотна калитки.</field>
        </record>
        <record id='OuterColor_Custom'>
            <field name='Label'>By RAL (4-digit number)</field>
            <field name='Description'>Цвет  полотна калитки.</field>
        </record>
        <record id='ColorType_Glossy'>
            <field name='Label'>Глянцевая</field>
            <field name='Description'></field>
        </record>
        <record id='ColorType_Mat'>
            <field name='Label'>Матовая</field>
            <field name='Description'></field>
        </record>
        <record id='WithLock_List'>
            <field name='Label'>Замок</field>
            <field name='Description'></field>
        </record>
        <record id='ExpendableMaterials_DHA'>
            <field name='Label'>Болт анкерный</field>
            <field name='Description'>Применяются при монтаже на фланцы, рекомендуется 4 шт. на один фланец.</field>
        </record>
        <record id='Packaging_Cardboard'>
            <field name='Label'>Carton</field>
            <field name='Description'>Выбор дополнительной упаковки в случае требований заказчика.</field>
        </record>
        <record id='Packaging_Wood'>
            <field name='Label'>Упаковка в дерево</field>
            <field name='Description'>Выбор дополнительной упаковки в случае требований заказчика.</field>
        </record>
        <record id='Note'>
            <field name='Label'></field>
            <field name='Description'>Selection of additional packaging if the customer requires it. Packaging on default: protective angles, stretch film.</field>
        </record>

        <!-- РАЗДЕЛ КОНСТАНТ -->
        <record id='default_width'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>800</field>
        </record>

        <record id='default_height'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>2050</field>
        </record>

        <record id='default_nonstandard_code'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>---</field>
        </record>

        <record id='default_square_clearance'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>100</field>
        </record>

        <record id='default_outer_color_standard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>6005</field>
        </record>

        <record id='default_outer_color_nonstandard'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_outer_color_custom'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>1000</field>
        </record>

        <record id='default_with_lock'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

        <record id='default_with_assembly'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>concreted_poles</field>
        </record>

        <record id='word_more'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>более</field>
        </record>

        <record id='word_less'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>менее</field>
        </record>

        <record id='word_width_more_then'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>ширина более</field>
        </record>

        <record id='word_and'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>и</field>
        </record>

        <record id='word_not_defined'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>not defined</field>
        </record>

        <record id='SquareClearanceMessage'>
            <field name='CurrentValue'>Величина просвета должна быть не менее 10 мм. и не более 200 мм.</field>
        </record>

        <record id='PackagingWoodMessage'>
            <field name='CurrentValue'>Нет упаковки в дерево</field>
        </record>

        <record id='default_image'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>STRING</field>
            <field name='CurrentValue'>configurators/dus931/images/</field>
        </record>

        <record id='margins'>
            <field name='Kind'>PROGRESS</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
            </field>
        </record>

        <record id='listSquareWidth'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
                800|= 800;
                900|= 900;
                1000|= 1000;
                1100|= 1100
            </field>
        </record>

        <record id='listSquareHeight'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
                1550|= 1550;
                1750|= 1750;
                2050|= 2050;
                2550|= 2550
            </field>
        </record>

        <record id='listOuterColorStandard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
                6005|RAL 6005 (зелёный)
            </field>
        </record>

        <record id='listOuterColorNonStandard'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
            </field>
        </record>

        <record id='listAssemblyType'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
                concreted_poles|Бетонирование столбов;
                concreted_rack|Бетонирование рамы;
                flange|Монтаж на фланцы
            </field>
        </record>

        <record id='listWithLock'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>LIST</field>
            <field name='CurrentValue'>
                0##
                no|no;
                AHF25|Замок в комплекте with нажимной ручкой|00000124753;
                AHR24-R004|Замок в комплекте with ручкой-скобой|00000131045:00000013508;
                AHR24-R00|Замок в комплекте with ручкой-скобой|00000131045:00000014110
            </field>
        </record>

        <record id='constSavedImage'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field>
        </record>

    </table>
</document>

