<?xml version="1.0" encoding="UTF-8"?>
<!-- Конфигуратор калитки для системы ограждений - артикул DUS-931 -->
<!-- Generated by Helpgen.py, version 2.37 beta ©  -->
<!-- Date: 2014-09-13 07:49 -->

<!DOCTYPE document
    [
        <!ELEMENT document (system, task, description, record+)>
            <!ATTLIST   document
                        id        ID        #REQUIRED
                        type      NMTOKEN   #REQUIRED
            >
        <!ELEMENT system EMPTY>
            <!ATTLIST   system
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT task EMPTY>
            <!ATTLIST   task
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT description EMPTY>
            <!ATTLIST   description
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT record (field+)>
            <!ATTLIST   record
                        id        ID        #REQUIRED
            >
        <!ELEMENT field ANY>
            <!ATTLIST   field
                        name      NMTOKEN   #REQUIRED
            >
    ]
>


<document id='variablesDescription' type='Respond'>
    <system id='-CIS' version='1'/>
    <task id='CALCHELPER' version='2'/>
    <description id='FenceWicketDUS931' version='1'/>

        <!-- РАЗДЕЛ ДЛЯ ПОЛЕЙ ФОРМЫ КОНФИГУРАТОРА -->
        <!-- Комплектация заказа -->

        <!-- Параметры проёма -->
        <!-- Ширина (B) -->
        <record id='SquareWidth_List'>
            <field name='Kind'>POP-UP MENU</field>
            <field name='Type'>LIST</field>
            <field name='GroupID'>ModelGroup</field>
            <field name='SubGroupID'>square_group</field>
            <field name='UnitID'>003</field>
            <field name='Style'>fontSize:14;fontFamily:Arial</field>
        </record>
        <!-- связь с 1С -->
        <record id='SquareWidth_up'>
            <field name='ID'>cp_width</field><field name='Kind'>CONSTANT</field><field name='Type'>NUMBER</field><field name='SubGroupID'>square_group</field>
        </record>
        <!-- Высота (H) -->
        <record id='SquareHeight_List'>
            <field name='Kind'>POP-UP MENU</field>
            <field name='Type'>LIST</field>
            <field name='GroupID'>ModelGroup</field>
            <field name='SubGroupID'>square_group</field>
            <field name='UnitID'>003</field>
            <field name='Style'>fontSize:14;fontFamily:Arial</field>
        </record>
        <!-- связь с 1С -->
        <record id='SquareHeight_up'>
            <field name='ID'>cp_height</field><field name='Kind'>CONSTANT</field><field name='Type'>NUMBER</field><field name='SubGroupID'>square_group</field>
        </record>
        <!-- Общая площадь проёма -->
        <record id='SquareAperture'>
            <field name='Kind'>DISPLAY FIELD</field>
            <field name='Type'>STRING</field>
            <field name='GroupID'>ModelGroup</field>
            <field name='UnitID'>055</field>
        </record>

        <!-- Просвет -->
        <!-- _________ -->
        <record id='SquareClearanceGroupTitle_1'>
            <field name='Kind'>DISPLAY FIELD</field>
            <field name='Type'>STRING</field>
            <field name='GroupID'>ModelGroup</field>
            <field name='Style'>fontWeight:bold;color:#aaaaaa;fontFamily:arial;fontSize:12</field>
        </record>
        <!-- Просвет (P) -->
        <record id='SquareClearance'>
            <field name='Kind'>INPUT FIELD</field>
            <field name='Type'>NUMBER</field>
            <field name='Format'>0-9::3.0</field>
            <field name='GroupID'>ModelGroup</field>
            <field name='CurrentValue'></field>
            <field name='UnitID'>003</field>
        </record>
        <!-- связь с 1С -->
        <record id='SquareClearance_up'>
            <field name='ID'>cp_clearance</field><field name='Kind'>CONSTANT</field><field name='Type'>NUMBER</field><field name='SubGroupID'>square_clearance_group</field>
        </record>

        <!-- Особенности конструкции -->
        <!-- Направление открытия -->
        <!-- Наружу -->
        <record id='Opening_Outside'>
            <field name='ID'>cp_door_opening_outside</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='SubGroupID'>shield_opening_group</field>
            <field name='CurrentValue'>false</field>
        </record>
        <!-- Внутрь -->
        <record id='Opening_Inside'>
            <field name='ID'>cp_door_opening_inside</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='SubGroupID'>shield_opening_group</field>
            <field name='CurrentValue'>true</field>
        </record>

        <!-- Положение петель -->
        <!-- Слева -->
        <record id='Hinge_Left'>
            <field name='ID'>cp_door_hinge_left</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='SubGroupID'>hinge_group</field>
            <field name='CurrentValue'>false</field>
        </record>
        <!-- Справа -->
        <record id='Hinge_Right'>
            <field name='ID'>cp_door_hinge_right</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='SubGroupID'>hinge_group</field>
            <field name='CurrentValue'>true</field>
        </record>

        <!-- Монтаж калитки -->
        <!-- _________ -->
        <record id='AssemblyGroupTitle_1'>
            <field name='Kind'>DISPLAY FIELD</field>
            <field name='Type'>STRING</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='Style'>fontWeight:bold;color:#aaaaaa;fontFamily:arial;fontSize:12</field>
        </record>
        <!-- Монтаж калитки -->
        <record id='AssemblyType_List'>
            <field name='ID'>cp_assembly_type</field>
            <field name='Kind'>POP-UP MENU</field>
            <field name='Type'>LIST</field>
            <field name='GroupID'>ProductInfoGroup</field>
            <field name='SubGroupID'>assembly_group</field>
        </record>
        <record id='assemblyType_up'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field><field name='SubGroupID'>assembly_group</field>
        </record>

        <!-- Дизайн -->
        <!-- Цвет полотна калитки -->
        <!-- Стандартный -->
        <record id='OuterColorStandard'>
            <field name='ID'>cp_outer_color_standard</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>outer_color_group</field>
            <field name='CurrentValue'>true</field>
        </record>
        <record id='OuterColor_List'>
            <field name='Kind'>POP-UP MENU</field>
            <field name='Type'>LIST</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>outer_color_group</field>
        </record>
        <!-- По образцу RAL (4-х значное число) -->
        <record id='OuterColor_Custom'>
            <field name='ID'>cp_outer_color_custom</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>outer_color_group</field>
            <field name='CurrentValue'>false</field>
        </record>
        <record id='OuterColor_Value'>
            <field name='Kind'>INPUT FIELD</field>
            <field name='Type'>NUMBER</field>
            <field name='Format'>0-9::4.0</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>outer_color_group</field>
        </record>
        <!-- связь с 1С -->
        <record id='outerColor_up'>
            <field name='ID'>cp_outer_color_value</field><field name='Kind'>CONSTANT</field><field name='Type'>STRING</field><field name='SubGroupID'>outer_color_group</field>
        </record>

        <!-- Тип краски -->
        <!-- Глянцевая -->
        <record id='ColorType_Glossy'>
            <field name='ID'>cp_color_type_glossy</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>color_type_group</field>
            <field name='CurrentValue'>true</field>
        </record>
        <!-- Матовая -->
        <record id='ColorType_Mat'>
            <field name='ID'>cp_color_type_mat</field>
            <field name='Kind'>RADIOBUTTON</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>SandwichPanelGroup</field>
            <field name='SubGroupID'>color_type_group</field>
            <field name='CurrentValue'>false</field>
        </record>

        <!-- Дополнительная комплектация -->
        <!-- Замок -->
        <!-- Замок -->
        <record id='WithLock_List'>
            <field name='ID'>cp_lock_model</field>
            <field name='Kind'>POP-UP MENU</field>
            <field name='Type'>LIST</field>
            <field name='GroupID'>HandleAndLockGroup</field>
            <field name='SubGroupID'>lock_group</field>
        </record>
        <record id='withLock_up'>
            <field name='Kind'>CONSTANT</field><field name='Type'>STRING</field><field name='SubGroupID'>lock_group</field>
        </record>

        <!-- Расходные материалы -->
        <!-- Болт анкерный -->
        <record id='ExpendableMaterials_DHA'>
            <field name='Kind'>CHECKBOX</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>ExpendableMaterialsGroup</field>
            <field name='SubGroupID'>expendable_materials_group</field>
            <field name='CurrentValue'>false</field>
        </record>
        <!-- связь с 1С -->
        <record id='ExpendableMaterials_DHA_Count'>
            <field name='ID'>00000013035</field>
            <field name='Kind'>INPUT FIELD</field>
            <field name='Type'>NUMBER</field>
            <field name='Format'>0-9::2.0</field>
            <field name='GroupID'>ExpendableMaterialsGroup</field>
            <field name='SubGroupID'>expendable_materials_group</field>
            <field name='CurrentValue'></field>
            <field name='UnitID'>796</field>
        </record>

        <!-- Упаковка изделия -->
        <!-- Картон -->
        <record id='Packaging_Cardboard'>
            <field name='ID'>CB000189689</field>
            <field name='Kind'>CHECKBOX</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>PackagingGroup</field>
            <field name='SubGroupID'>packaging_group</field>
            <field name='CurrentValue'>false</field>
        </record>
        <!-- Упаковка в дерево -->
        <record id='Packaging_Wood'>
            <field name='ID'>CB000189688</field>
            <field name='Kind'>CHECKBOX</field>
            <field name='Type'>BOOLEAN</field>
            <field name='GroupID'>PackagingGroup</field>
            <field name='SubGroupID'>packaging_group</field>
            <field name='CurrentValue'>false</field>
        </record>

        <!-- Примечание -->
        <record id='Note'>
            <field name='ID'>cp_note</field>
            <field name='Kind'>INPUT AREA</field>
            <field name='Type'>STRING</field>
            <field name='GroupID'>NoteGroup</field>
            <field name='SubGroupID'>note_group</field>
        </record>

        <!-- РАЗДЕЛ КОНСТАНТ -->
        <record id='minSquareClearance'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>NUMBER</field>
            <field name='CurrentValue'>10</field>
        </record>

        <record id='maxSquareClearance'>
            <field name='Kind'>CONSTANT</field>
            <field name='Type'>NUMBER</field>
            <field name='CurrentValue'>200</field>
        </record>

        <record id='construct_default'>
            <field name='ID'>constructCB000002708</field>
            <field name='Kind'>PROGRESS</field>
            <field name='Type'>NUMBER</field>
        </record>

</document>

