<?xml version="1.0" encoding="UTF-8"?>
<!-- Конфигуратор секционных промышленных ворот стандартной серии - артикул DUS480 -->
<!-- Generated by Helpgen.py, version 2.44 beta ©  -->
<!-- Date: 2015-06-25 01:03 -->

<!DOCTYPE document
    [
        <!ELEMENT document (system, task, description, lanquage, table+)>
            <!ATTLIST   document
                        id        ID        #REQUIRED
                        type      NMTOKEN   #REQUIRED
            >
        <!ELEMENT system EMPTY>
            <!ATTLIST   system
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT task EMPTY>
            <!ATTLIST   task
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT description EMPTY>
            <!ATTLIST   description
                        id        ID        #REQUIRED
                        version   NMTOKEN   #REQUIRED
            >
        <!ELEMENT lanquage EMPTY>
            <!ATTLIST   lanquage
                        id        ID        #REQUIRED
            >
        <!ELEMENT table (record+)>
            <!ATTLIST   table
                        name      NMTOKEN   #REQUIRED
            >
        <!ELEMENT record (field+)>
            <!ATTLIST   record
                        id        ID        #REQUIRED
            >
        <!ELEMENT field ANY>
            <!ATTLIST   field
                        name      NMTOKEN   #REQUIRED
            >
    ]
>


<document id='variablesContent' type='Respond'>
    <system id='-CIS' version='1'/>
    <task id='CALCHELPER' version='2'/>
    <description id='SectionalDoorsDUS480' version='1'/>
    <lanquage id='DEU'/>

    <table name='KnowledgeRepository'>
        <record id='c0'>
            <field name='image'>icon1.png</field>
            <field name='description'>Produkt- Configurator (WEB-Assistent). Benutzerhandbuch.</field>
            <field name='location'>documents/HelperInfo.pdf</field>
        </record>
        <record id='c1'>
            <field name='image'>icon1.png</field>
            <field name='description'>Каталог комплектации для секционных ворот .</field>
            <field name='location'>documents/katalog_sekcionnie_sistemi_2013-RUS.pdf</field>
        </record>
    </table>

    <!-- ОПИСАНИЕ ГРУПП -->
    <table name='GroupAndSubgroup'>
        <record id='CompoundGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Bestellmöglichkeiten</field>
        </record>
        <record id='GarageInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Die Parameter der Öffnung</field>
        </record>
        <record id='platband_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Sturzhöhe</field>
        </record>
        <record id='left_side_width_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Linker Seitenanschlag</field>
        </record>
        <record id='right_side_width'>
            <field name='TypeID'>2</field>
            <field name='Description'>Rechter Seitenanschlag</field>
        </record>
        <record id='depth_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Raumtiefe</field>
        </record>
        <record id='wall_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Material der Wände</field>
        </record>
        <record id='ceiling_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Material der Decke</field>
        </record>
        <record id='lintel_material_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Material des Sturzes</field>
        </record>
        <record id='ProductInfoGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Konstruktionsmerkmale</field>
        </record>
        <record id='lifting_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Typ des Beschlags</field>
        </record>
        <record id='slope_angle_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Neigungswinkel</field>
        </record>
        <record id='lifting_cycle_count_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Количество циклов (шт)</field>
        </record>
        <record id='SandwichPanelGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Sandwich-Paneele</field>
        </record>
        <record id='outer_side_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Design</field>
        </record>
        <record id='outer_composition_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Struktur</field>
        </record>
        <record id='outer_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Farbe</field>
        </record>
        <record id='InnerSideGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Оформление с внутренней стороны</field>
        </record>
        <record id='DoorGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Schlupftür</field>
        </record>
        <record id='door_setup_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Schlupftür einbauen</field>
        </record>
        <record id='door_type_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Art der Schlupftür</field>
        </record>
        <record id='door_side_width_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Ширина проёма для калитки</field>
        </record>
        <record id='door_side_height_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Высота проёма для калитки</field>
        </record>
        <record id='door_position_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Die Position der Schlupftür am Torblatt</field>
        </record>
        <record id='hinge_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Position der Scharniere</field>
        </record>
        <record id='door_sash_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет профиля калитки</field>
        </record>
        <record id='DoorLockGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Замки и задвижки</field>
        </record>
        <record id='lock_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Замок</field>
        </record>
        <record id='dleGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Ручки</field>
        </record>
        <record id='handle_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Дополнительная ручка</field>
        </record>
        <record id='AcrylicWindowGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Acryl Fenster</field>
        </record>
        <record id='acrylic_window_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Anzahl nach Arten</field>
        </record>
        <record id='window_note_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Hinweis zur Fensterwahl</field>
        </record>
        <record id='GuardDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Schutzvorrichtungen</field>
        </record>
        <record id='DriveGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Automatik</field>
        </record>
        <record id='drive_setup_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Antrieb einbauen</field>
        </record>
        <record id='drive_model_overhead_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Decke</field>
        </record>
        <record id='drive_model_power_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Wellig</field>
        </record>
        <record id='drive_model_manual_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Ручной</field>
        </record>
        <record id='ProductConfirmationGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Design control</field>
        </record>
        <record id='ControlDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Steuergeräte</field>
        </record>
        <record id='SecurityDevicesGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Sicherheitsvorrichtungen</field>
        </record>
        <record id='EquipmentGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Optionales Zubehör</field>
        </record>
        <record id='edging_pipe_color_group'>
            <field name='TypeID'>2</field>
            <field name='Description'>Цвет окантовочной трубы</field>
        </record>
        <record id='ExpendableMaterialsGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Verbrauchsmaterial</field>
        </record>
        <record id='NoteGroup'>
            <field name='TypeID'>1</field>
            <field name='Description'>Hinweis</field>
        </record>
    </table>

    <!-- РАЗДЕЛ ДЛЯ ПОЛЕЙ ФОРМЫ КОНФИГУРАТОРА -->
    <table name='HelperTaskDescription'>
        <record id='Compound_Default'>
            <field name='Label'>Комплект ворот</field>
            <field name='Description'></field>
        </record>
        <record id='Compound_ShieldOnly'>
            <field name='Label'>Щит ворот без комплектации</field>
            <field name='Description'></field>
        </record>
        <record id='Compound_SlideRailsOnly'>
            <field name='Label'>Направляющие ворот без комплектации</field>
            <field name='Description'></field>
        </record>
        <record id='SquareWidth'>
            <field name='Label'>Breite (B)</field>
            <field name='Description'>Der Wert der Breite der Öffnung für die Toreinbau.</field>
        </record>
        <record id='SquareHeight'>
            <field name='Label'>Höhe (H)</field>
            <field name='Description'>Der Wert der Höhe der Öffnung für den Toreinbau.</field>
        </record>
        <record id='SquareAperture'>
            <field name='Label'>Die Gesamtfläche der Öffnung</field>
            <field name='Description'>Der Wert der Höhe der Öffnung für den Toreinbau.</field>
        </record>
        <record id='Platband_Size'>
            <field name='Label'>Sturzhöhe (h)</field>
            <field name='Description'>Sturzhöhe- ist der Abstand zwischen der oberen Öffnungskante und der Decke.</field>
        </record>
        <record id='LeftSideWidth'>
            <field name='Label'>Linker Seitenanschlag (b1)</field>
            <field name='Description'>Der Abstand von der Kante der Öffnung bis zur linken Wand des Raumes.</field>
        </record>
        <record id='RightSideWidth'>
            <field name='Label'>Rechter Seitenanschlag (b2)</field>
            <field name='Description'>Der Abstand von der Kante der Öffnung bis zur rechten Wand des Raumes.</field>
        </record>
        <record id='SquareDepthGroupTitle_1'>
            <field name='CurrentValue'>_________</field>
            <field name='Description'></field>
        </record>
        <record id='SquareDepth'>
            <field name='Label'>Raumtiefe (L)</field>
            <field name='Description'></field>
        </record>
        <record id='WallMaterialTitle_1'>
            <field name='CurrentValue'>Материал стен:</field>
            <field name='Description'>Material der Öffnung für die richtige Wahl der Befestigungselemente.</field>
        </record>
        <record id='WallMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Material der Öffnung für die richtige Wahl der Befestigungselemente.</field>
        </record>
        <record id='CeilingMaterialTitle_1'>
            <field name='CurrentValue'>Материал потолка:</field>
            <field name='Description'>Тип материала потолка для правильного выбора крепежа.</field>
        </record>
        <record id='CeilingMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Тип материала потолка для правильного выбора крепежа.</field>
        </record>
        <record id='LintelMaterialTitle_1'>
            <field name='CurrentValue'>Материал притолоки:</field>
            <field name='Description'>Тип материала притолоки для правильного выбора крепежа.</field>
        </record>
        <record id='LintelMaterial_List'>
            <field name='Label'></field>
            <field name='Description'>Тип материала притолоки для правильного выбора крепежа.</field>
        </record>
        <record id='LiftingType_LowRollFront'>
            <field name='Label'>Низкий (барабан спереди)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_LowRollBack'>
            <field name='Label'>Низкий (барабан сзади)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Default'>
            <field name='Label'>Standard</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Downward'>
            <field name='Label'>Стандартный наклонный</field>
            <field name='Description'>Значение вводимое в поле «Угол подъема (град.)» должно быть кратным 5. (Пример: 5,10,15,20……65)».</field>
        </record>
        <record id='LiftingType_High'>
            <field name='Label'>Высокий</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_HighRollBottom'>
            <field name='Label'>Высокий (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_HighDownward'>
            <field name='Label'>Высокий наклонный</field>
            <field name='Description'>Значение вводимое в поле «Угол подъема (град.)» должно быть кратным 5. (Пример: 5,10,15,20……65)».</field>
        </record>
        <record id='LiftingType_HighDownwardRollBottom'>
            <field name='Label'>Высокий наклонный (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_Vertical'>
            <field name='Label'>Вертикальный</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingType_VerticalRollBottom'>
            <field name='Label'>Вертикальный (вал снизу)</field>
            <field name='Description'></field>
        </record>
        <record id='SlopeAngle'>
            <field name='Label'>Угол наклона (град.)</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25130LG'>
            <field name='Label'>25 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25130'>
            <field name='Label'>50 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25131LG'>
            <field name='Label'>75 000</field>
            <field name='Description'></field>
        </record>
        <record id='LiftingCycleCount_DH25131'>
            <field name='Label'>100 000</field>
            <field name='Description'></field>
        </record>
        <record id='ProductInfoGroupTitle_1'>
            <field name='CurrentValue'>________________________</field>
            <field name='Description'></field>
        </record>
        <record id='IsOptimizeLifting'>
            <field name='Label'>Оптимальный подъём</field>
            <field name='Description'></field>
        </record>
        <record id='ShieldOuterDesignTitle_1'>
            <field name='CurrentValue'>Внешняя сторона</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterDesign_List'>
            <field name='Label'>Design</field>
            <field name='Description'>Дизайн сэндвич-панелей.</field>
        </record>
        <record id='OuterComposition_List'>
            <field name='Label'>Struktur</field>
            <field name='Description'>Структура поверхности сэндвич-панелей.</field>
        </record>
        <record id='OuterColorStandard'>
            <field name='Label'>Standard -Farben (RAL)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorNonStandard'>
            <field name='Label'>Нестандартный</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColorWood'>
            <field name='Label'>Имитации дерева</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='OuterColor_Custom'>
            <field name='Label'>Individuell (nach Modell)</field>
            <field name='Description'>Цвет сэндвич-панелей.</field>
        </record>
        <record id='DoorSetup'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V2'>
            <field name='Label'>V2</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V3'>
            <field name='Label'>V3</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V4'>
            <field name='Label'>V4</field>
            <field name='Description'></field>
        </record>
        <record id='DoorType_V5'>
            <field name='Label'>V5</field>
            <field name='Description'></field>
        </record>
        <record id='DoorSideGroupTitle_1'>
            <field name='CurrentValue'>Размеры калитки:</field>
            <field name='Description'>Ширина калитки от 800 до 1000 мм, калитка версии V3 шириной 800 мм.</field>
        </record>
        <record id='DoorSideWidth'>
            <field name='Label'>Ширина (b)</field>
            <field name='Description'>Ширина калитки от 800 до 1000 мм, калитка версии V3 шириной 800 мм.</field>
        </record>
        <record id='DoorSideHeight'>
            <field name='Label'>Высота (h)</field>
            <field name='Description'>Допустимые значения высоты калитки от 1800 до 2300 мм. В зависимости от раскроя панелей полотна ворот высота калитки может варьироваться от 0 до 150 мм.</field>
        </record>
        <record id='DoorSideGroupTitle_2'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'>Допустимые значения высоты калитки от 1800 до 2300 мм. В зависимости от раскроя панелей полотна ворот высота калитки может варьироваться от 0 до 150 мм.</field>
        </record>
        <record id='DoorPosition_Left'>
            <field name='Label'>Links</field>
            <field name='Description'>Vorgegebene Lage der Schlupftür von der linken Seite des Torblattes in mm. Die Stelle wird durch einen Beobachter ermittelt., sich im Innenraum befindend.</field>
        </record>
        <record id='DoorPosition_Center'>
            <field name='Label'>Zentral</field>
            <field name='Description'>Vorgegebene Lage der Schlupftür von der linken Seite des Torblattes in mm. Die Stelle wird durch einen Beobachter ermittelt., sich im Innenraum befindend.</field>
        </record>
        <record id='DoorPosition_Right'>
            <field name='Label'>Rechts</field>
            <field name='Description'>Vorgegebene Lage der Schlupftür von der linken Seite des Torblattes in mm. Die Stelle wird durch einen Beobachter ermittelt., sich im Innenraum befindend.</field>
        </record>
        <record id='Hinge_Left'>
            <field name='Label'>Links</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='Hinge_Right'>
            <field name='Label'>Rechts</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='DoorSideGroupTitle_3'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'>Положение петель определяет тип открытия одностворчатой двери (правостороннее или левостороннее), направление определяется наблюдателем, находящимся внутри помещения (гаража).</field>
        </record>
        <record id='DoorSashColorStandard'>
            <field name='Label'>Standard</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='DoorSashColor_List'>
            <field name='Label'>Profilfarbe</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='DoorSashColor_BySample'>
            <field name='Label'>Gem. RAL- Farbmuster (4-stellig)</field>
            <field name='Description'>Цвет алюминиевых профилей рамы калитки.</field>
        </record>
        <record id='WithLock_List'>
            <field name='Label'>Замок</field>
            <field name='Description'></field>
        </record>
        <record id='WithHandle_List'>
            <field name='Label'>Дополнительная ручка</field>
            <field name='Description'>Можно установить только одну дополнительную ручку.</field>
        </record>
        <record id='Window_DH85603'>
            <field name='CurrentValue'>635x330 mm, акриловое</field>
            <field name='Description'>Art und Größe des Fensters, das im Torblatt installiert werden.</field>
        </record>
        <record id='Window_DH85602'>
            <field name='CurrentValue'>607x202 mm, акриловое</field>
            <field name='Description'>Art und Größe des Fensters, das im Torblatt installiert werden.</field>
        </record>
        <record id='Window_RingSilver'>
            <field name='CurrentValue'>Окно круглое, диаметр 360 мм, металик</field>
            <field name='Description'>Art und Größe des Fensters, das im Torblatt installiert werden.</field>
        </record>
        <record id='WindowNote'>
            <field name='Label'>Hinweis zur Fensterwahl</field>
            <field name='Description'>Beschreibung der Anordnung der Fenster am Torblatt.</field>
        </record>
        <record id='WithGuardRope'>
            <field name='Label'>Seilbruchsicherung</field>
            <field name='Description'></field>
        </record>
        <record id='WithGuardBreakRope'>
            <field name='Label'>Seilbruchsicherung</field>
            <field name='Description'></field>
        </record>
        <record id='DriveSetup'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSetupFuture'>
            <field name='Label'>Zukünftige Installation Wellenantriebs</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSetupGroupTitle_3'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelOverheadStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelGroupTitle_1'>
            <field name='CurrentValue'>Комплект потолочного привода:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelGroupTitle_2'>
            <field name='CurrentValue'>Привод:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500PROWHITE'>
            <field name='Label'>SECTIONAL-500PRO-WHITE S=8 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500PROBLACK'>
            <field name='Label'>SECTIONAL-500PRO-BLACK S=8 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE500'>
            <field name='Label'>SECTIONAL-500</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE750'>
            <field name='Label'>SECTIONAL-750</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_FAST750'>
            <field name='Label'>FAST-750</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE1000'>
            <field name='Label'>SECTIONAL-1000, S=13 кв.м</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXOverhead_SE1200'>
            <field name='Label'>SECTIONAL-1200</field>
            <field name='Description'></field>
        </record>
        <record id='OverheadDeviceGroupTitle_1'>
            <field name='CurrentValue'>Schienensatz für decken Antrieb</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerGroupTitle_1'>
            <field name='CurrentValue'>Комплект вального привода:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelPowerGroupTitle_2'>
            <field name='CurrentValue'>Привод:</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXPower_SE524'>
            <field name='Label'>GFA SE-5.24 220V</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXPower_SE1421'>
            <field name='Label'>GFA SE-14.21 380V</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSideGroupTitle_1'>
            <field name='CurrentValue'>Сторона установки привода:</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSide_Right'>
            <field name='Label'>Rechts</field>
            <field name='Description'></field>
        </record>
        <record id='PowerDriveSide_Left'>
            <field name='Label'>Links</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelManualStandard'>
            <field name='Label'></field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025M'>
            <field name='Label'>Handkettenzug</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025KIT'>
            <field name='Label'>Handkettenzug mit Rolle</field>
            <field name='Description'></field>
        </record>
        <record id='DriveModelXManual_25025P'>
            <field name='Label'>Ручной цепной привод со звёздочкой</field>
            <field name='Description'></field>
        </record>
        <record id='DriveExtraChainGroupTitle_1'>
            <field name='CurrentValue'>__________</field>
            <field name='Description'></field>
        </record>
        <record id='DriveExtraChain'>
            <field name='Label'>Дополнительная цепь</field>
            <field name='Description'>Необходимое количество дополнительной цепи рассчитывается в метрах с округлением до ближайшего целого в большую сторону.</field>
        </record>
        <record id='ControlDevicesGroup_COMMAND433'>
            <field name='CurrentValue'>Кнопочная панель радиоуправления COMMAND433</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_XT2_868SLH'>
            <field name='CurrentValue'>Пульт 2-канальный  (БЕЛЫЙ)</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_RX_RP1_868_SLH'>
            <field name='CurrentValue'>Приемник 868 МГЦ (встраеваемый) со встр. антеной</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_Transmitter_2'>
            <field name='CurrentValue'>Пульт  2-х канальный, 433MHz</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_Transmitter_4'>
            <field name='CurrentValue'>4-Tasten-Handsender 433 MHz (), 433MHz</field>
            <field name='Description'></field>
        </record>
        <record id='ControlDevicesGroup_RCBLACK_4'>
            <field name='CurrentValue'>4-Tasten-Handsender RCBLACK-4 433 MHz Premium, schwarz, 433MHz</field>