<?xml version="1.0" encoding="UTF-8"?>
<!-- Контроль параметров комплектации -->

<!DOCTYPE document
	[
		<!ELEMENT document (system, task, description, construct+)>
			<!ATTLIST	document
						id		ID		#REQUIRED
						type	NMTOKEN	#REQUIRED
			>
			<!ELEMENT system EMPTY>
				<!ATTLIST	system
							id		ID		#REQUIRED
							version	NMTOKEN	#REQUIRED
				>
			<!ELEMENT task EMPTY>
				<!ATTLIST	task
							id		ID		#REQUIRED
							version	NMTOKEN	#REQUIRED
				>
			<!ELEMENT description EMPTY>
				<!ATTLIST	description
							id		ID		#REQUIRED
							version	NMTOKEN	#REQUIRED
				>
			<!ELEMENT construct (field+)>
				<!ATTLIST	construct
							id		ID		#REQUIRED
				>
				<!ELEMENT field ANY>
						<!ATTLIST	field
									name	NMTOKEN	#REQUIRED
						>
	]
>

<document id='validationList' type='Respond'>
	<system id='-CIS' version='1'/>
	<task id='CALCHELPER' version='2'/>
	<description id='Construction Field Items Restrictions' version='1'/>

	<!-- Секционные ворота. Калитка. «Тип калитки V2 не доступен для московского региона» -->
	<construct id="LocalDoorsDoorTypeV2">
		<field name='Name'>DoorType</field>
		<field name='Enabled'>On</field>
		<field name='Value'>V2</field>
		<field name='Region'>moscow</field>
	</construct>
</document>
